### ISSUE TITLE
VetSim

### ISSUE THREAD

**Issue by RealJohnSmith** [KSU-CS-Software-Engineering/VetMedSim#1]
Why did you call this VetSim? You should rename back to Dogtor, that was way better name...

**Comment by ksu-shanemat** [comment]
Unfortunately, the choice of name is not our choice. If this troubles you a lot however, you can contact Keleigh Shettler (krickman@vet.k-state.edu).

**Comment by RealJohnSmith** [comment]
I will keep reopening this issue until you rename it. 
The name “Dogtor” is pretty neat, but the original “VetSim” is crap.
